name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env file for tests
        run: echo "PORT=${{ secrets.PORT }}" > .env

      - name: Run tests
        run: yarn test

      - name: Clean backend directory
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf ${{ secrets.SSH_PATH }}/*

      - name: Upload backend files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: .
          target: ${{ secrets.SSH_PATH }}
          debug: true

      - name: Create .env file on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "PORT=${{ secrets.PORT }}" > ${{ secrets.SSH_PATH }}/.env

      - name: Install deps & restart backend
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            yarn install --production --frozen-lockfile
            pm2 reload fastify-backend || pm2 start src/server.js --name fastify-backend
